gh_repo: bhi
app_title: Baltic
scenario_dirs: baltic2015
gh_owner: OHI-Science
gh_branch_data: draft
gh_branch_app: app
app_url: http://ohi-science.nceas.ucsb.edu/bhi
projection: Mercator
map_shrink_pct: 10.0
debug: no
ohirepos_commit: 17cfede2a32970ec356cf576375e68d0932a1b1f
last_updated: 17087.0
