gh_repo: bhi
app_title: Baltic
scenario_dirs: baltic2015
gh_owner: OHI-Science
gh_branch_data: draft
gh_branch_app: app
app_url: http://ohi-science.nceas.ucsb.edu/bhi
projection: Mollweide
map_shrink_pct: 10.0
debug: no
ohirepos_commit: 7c52c23b214bbbdf9505c39381557d0a3b5d5203
last_updated: 17077.0
