gh_repo: bhi
app_title: Baltic
scenario_dirs: baltic2015
gh_owner: OHI-Science
gh_branch_data: draft
gh_branch_app: app
app_url: http://ohi-science.nceas.ucsb.edu/bhi
projection: Mercator
map_shrink_pct: 10.0
debug: no
ohirepos_commit: 78221328ae0773611829a7bf45992beca197af96
last_updated: 17077.0
