# configuration for https://ohi-science.nceas.ucsb.edu/bhi
study_area:       Baltic
git_owner:        OHI-Science
git_repo:         bhi
git_slug:         OHI-Science/bhi
git_url:          https://github.com/OHI-Science/bhi
app_url:          http://ohi-science.nceas.ucsb.edu/bhi
default_branch:   published
default_scenario: baltic2015
debug:            False
last_updated:     2015-08-25
ohicore_app:
  git_owner: ohi-science
  git_repo: ohicore
  git_branch: dev
  git_commit: 41ea1726ba08bf1727d6fca34949db12b9d9fa1c

tabs_hide:        
- Calculate
- Report

