gh_repo: bhi
study_area: Baltic
scenario_dirs: baltic2015
gh_owner: OHI-Science
gh_branch_data: draft
gh_branch_app: app
app_url: http://ohi-science.nceas.ucsb.edu/bhi
projection: Mercator
map_shrink_pct: 10.0
debug: no
ohirepos_commit: 91f077d8e3f5fc08e21b04eab26c87d2050b6e9e
last_updated: 17098.0
