---
title: "AO.Rmd"
output: html_document
---

### 1.1 Goal Description

Artisanal fishing, often also called small-scale fishing, provides a critical source of food, nutrition, poverty alleviation and livelihood opportunities for many people around the world, in particular in developing nations. This goal measure whether people who need to fish on a small, local scale have the opportunity to do so. It has three sub-components: stock, access, and need. A score of 100 means the country or region is meeting the needs of artisanal fishermen or communities by implementing institutional supports, providing access to near-shore water, and maintaining the health of targeted species. 

For the Baltic regions, we focus on the **stock** sub-component and will use this as a proxy for the entire goal. 

### 1.2 Model & Data 

The AO model assesses the health of fish stocks, represented by the mean of two Core Indicators for stock abundance prepared by HELCOM: 

- [HELCOM Core Indicator Abundance of coastal fish key functional groups](http://helcom.fi/baltic-sea-trends/indicators/abundance-of-coastal-fish-key-functional-groups/)  and 
- [HELCOM Core Indicator Abundance of key coastal fish species](http://helcom.fi/baltic-sea-trends/indicators/abundance-of-key-coastal-fish-species) 

Each of the indicators was then scaled between 0 and 1. 

### 1.3 Reference points 

Reference point was the maximum possible good environmental status (value = 1). 

### 1.4 Other considerations for _OHI-BHI 2.0_

Stock was one component of the AO goal. Model could be updated with parameters representing access and need of artisanal fishing opportunities in the future. 



