### Goal Description

*Mariculture a sub-goal of the Food Provisioning (FP) goal (farming fish and shellfish in the ocean) is not a large industry in the Baltic, but it does provide some food production. Data were available for parts of Denmark, Sweden, Germany, and Finland. All other BHI regions are scored as NA, and thus MAR will not contribute to the overall FP goal score. Fos this sub-goal rainbow trout production was used.* 


### Model & Data
 
*Tonnes of mariculture production data were collected from country databases or reports:*

- *Sweden [Jorbruksverket](http://www.scb.se/sv_/Hitta-statistik/Statistik-efter-amne/Jord--och-skogsbruk-fiske/Vattenbruk/Vattenbruk/)*  

- *Denmark [Danish Agrifish Agency (Ministry of Environment and Food of Denmark)](http://agrifish.dk/fisheries/fishery-statistics/aquaculture-statistics/#c32851). On locations from NaturErhvervstyrelsen: The North Sea is very rough, hence there is no sea farms located in the North Sea side of Denmark, and the data on our home page only includes farms placed in the waters you are interested in. There is a map in this [report](http://www.akvakultur.dk/akvakultur%20i%20DK.htm) showing sea farms in Denmark. It’s a bit old (2003), but area wise it haven’t changed much.*

- *Finland [Natural Resources Institute](http://statdb.luke.fi/PXWeb/pxweb/fi/LUKE/LUKE__06%20Kala%20ja%20riista__02%20Rakenne%20ja%20tuotanto__10%20Vesiviljely/?tablelist=true&rxid=5211d344-451e-490d-8651-adb38df626e1). Data were available as total marine production by region.  Data were also available as total production per fish species.  Rainbow trout dominated the total fish production.  The data have been converted to the total production by region to rainbow trout production by region by using the country wide percent rainbow trout of the marine production in each year.  (The other minor contributions to total production were European whitefish, Trout, other species, Roe of rainbow trout, roe of european whitefish).*  

- *Production data for Germany were obtained from the [FAO FishStatJ](http://www.fao.org/fishery/statistics/software/fishstatj/en#downlApp) Global workspace, Aquaculture Production (Quantities and values) 1950-2014 (Release date: March 2016).

- *Data were downloaded for all nine Baltic countries. The Baltic sea falls within the [aquaculture area to 'Atlantic, Northeast'](http://www.fao.org/fishery/cwp/handbook/h/en). The environment type was required to be brackish to be considered Baltic Sea production.*

*The data were scaled according to the mariculture sustainability index (SMI). The SMI is the average of the three subindices traditionally used in the OHI framework. Trujillo's study^1^ included 13 subindices in total but only 3 of them are relevant for assessing the sustainability of mariculture : waster water treatment, usage of fishmeal and hatchery vs wild origin of seeds. Since Rainbow trout SMI is only included for Sweden. The mean value 5.3 was rescaled between 0-1 to 0.53. This value is then applied to Denmark and Finland.*

*Trujillo, P., (2008). Using a mariculture sustainability index to rank countries’ performance. Pp. 28-56 In: Alder, J. and D. Pauly (eds.). 2008.  A comparative assessment of biodiversity, fisheries and aquaculture in 53 countries’ Exclusive Economic Zones.’ Fisheries Centre Research Reports. Fisheries Centre, University of British Columbia*

### Reference points

*needs to be decided !!*

### Other considerations for _OHI-BHI 2.0_

*link to [prep files](https://github.com/OHI-Science/bhi/blob/draft/baltic2015/prep/MAR/mar_prep.md)*

*external advisors/goalkeepers: Data were compiled primarily by Ginnette Flores Carmenate.* 
