### Goal Description

Tourism in coastal areas is a major component of thriving coastal communities and a measure of how much people value ocean systems, i.e. by traveling to coastal and ocean areas. This goal is not about the revenue or livelihoods that are generated by tourism and recreation (that is captured in the livelihoods goal) but instead captures the value that people have for experiencing and enjoying coastal areas. A score of 100 means a region utilizes its full recreational potential without harming the ecosystem. <!---**In the BHI, ....**--->


### Model & Data


Data for each country were downloaded from the [EU-Study on Blue Growth](https://webgate.ec.europa.eu/maritimeforum/node/3550), Maritime Policy and the EU Strategy for the Baltic Sea Region” identified the potential for Blue Growth in each of the EU Member States (MS) of the Baltic Sea Region (BSR) and at sea basin level.

<!---
The tourism model incorporates the nights of stay in accommodations and compare that to the reference point. 

We used Eurostat dataset on [nights spent at tourist accommodation establishments](http://appsso.eurostat.ec.europa.eu/nui/show.do?dataset=tour_occ_nin2&lang=en) by all NUTS regions. [tour_occ_nin2] 
--->

### Reference points

*to be determined*
<!---
103% of the highest number of night of stay in the past five years. This is based on [EU's Blue Growth Strategy](http://ec.europa.eu/maritimeaffairs/policy/coastal_tourism/index_en.htm), which states "the coastal and maritime tourism sector has been identified as an area with special potential to foster a smart, sustainable and inclusive Europe. It is the biggest maritime sector in terms of gross value added and employment and is expected to grow by 2-3% by 2020." 
--->


### Considerations for *BHI 2.0*

<!---MISSING data for region 19, 22, 30, 33 --->

### Other information

