---
title: "Data source table"
output: github_document
---

This table was prepared for BHI by Jennifer Griffiths in July 2016 to document the data sources used in the preparation of data layers for BHI.

| Source Ref Number 	| BHI Component 	| Data source 	| Web links 	| Spatial attributes 	| Temporal Attributes 	|
|--|-----|------------|-------------------|-----------------------|-----------------------------|
| 1 	| AO stock 	| Assessment of coastal fish stock monitoring station Good Environmental Status provided by Jens Olsson with the FISH-PRO project. Key species and key functional group core indicators.  Raw data of coastal fish CPUE by monitoring station also provided for calculating trend. 	| http://www.helcom.fi/helcom-at-work/projects/fish-pro/ 	| Unique monitoring locations (point sampling locations, except Finland which uses ICES assessment areas) 	| Annual time series. 	|
|  	|  	|  	|  	|  	| Variable length between 1998-2013 	|
|  	|  	|  	| http://helcom.fi/baltic-sea-trends/indicators/abundance-of-key-coastal-fish-species 	|  	|  	|
|  	|  	|  	|  	|  	|  	|
|  	|  	|  	| http://www.helcom.fi/helcom-at-work/projects/fish-pro/ 	|  	|  	|
| 2 	| CS 	| Zostera meadows spatial coverage with attributes of “sparse” and “dense”. 	| HELCOM Marine Spatial Planning Map Service Select - Marine Spatial Planning - Ecology - Ecosystem Health status Data layer - "Zostera Meadows" 	| Baltic Sea coverage 	| Data compiled in 2009-2010 	|
| 3 	| CW NUT 	| Secchi depth observations 	| ICES Data extracted from database and sent by Hjalte Parner. * "extraction from our database classified into HELCOM Assessment Units – HELCOM sub basins with coastal WFD water bodies or water types" 	| Baltic Sea, lat-lon locations 	| 2000-2013 	|
|  	|  	|  	| SMHI Downloaded from SMHI Shark database on 23 February 2016 by Lena Viktorsson. * Download notes: datatyp: Physical and Chemical; Parameter: secchi depth Lena did not exclude any data when she downloaded it. 	|  	|  	|
| 4 	| CW CON 	| PCB concentrations in herring (ICES 6 PCB congeners: 28,52,101,138,153,180) 	| ICES DOME database http://dome.ices.dk/views/ContaminantsBiota.aspx 	| Baltic Sea, lat-lon locations 	|  	|
|  	|  	|  	| Downloaded 22 April 2016 by Jennifer Griffiths Data selections: Year - 1990-2014 Purpose of monitoring = All Country = ALL Monitoring Program = ALL Parameter Group = Chlorobiophenyls Reporting Laboratory = All Analytical laboratory = All Geographical Areas = (HELCOM) ALL HELCOM Sub-basins 	|  	|  	|
| 5 	| CW CON 	| Dioxins and dioxin-like PCB concentrations in herring, TEQ values 	| ICES DOME database http://dome.ices.dk/views/ContaminantsBiota.aspx 	| Baltic Sea, lat-lon locations, all Swedish locations 	| 2001-2014 	|
|  	|  	|  	| Downloaded on 11 May 2016 by Jennifer Griffiths Selections: Year - 1998-2015 (earliest allowed) Purpose of monitoring = All Country = ALL MOnitoring Program = ALL Parameter Group = Dioxins Reporting Laboratory = All Analytical laboratory = All Geographical Areas = (HELCOM) ALL HELCOM Sub-basins 	|  	|  	|
|  	|  	|  	| WHO TEQ values: http://www.who.int/ipcs/assessment/tef_values.pdf 	|  	|  	|
| 6 	| CW CON 	| PFOS concentrations in herring 	| ICES DOME database 	| For herring, Swedish lat-lon locations in all years, Polish lat-lon locations in 2014. 	| 2005-2014 	|
|  	|  	|  	| http://dome.ices.dk/views/ContaminantsBiota.aspx 	|  	|  	|
|  	|  	|  	| Download on 15 July 2016 by Jennifer Griffiths 	|  	|  	|
|  	|  	|  	| Data selections 	|  	|  	|
|  	|  	|  	| Year: 2005- 2014 	|  	|  	|
|  	|  	|  	| Purpose of Monitoring: All 	|  	|  	|
|  	|  	|  	| Monitoring Program: All 	|  	|  	|
|  	|  	|  	| Parameter group = Organofluorines 	|  	|  	|
|  	|  	|  	| Reporting Laboratory = All 	|  	|  	|
|  	|  	|  	| Analytical laboratory = All 	|  	|  	|
|  	|  	|  	| Geographical Areas = (HELCOM) ALL HELCOM Sub-basins 	|  	|  	|
| 7 	| CW TRA 	| Modeled plastic waste that is mismanaged and has the potential to enter the ocean 	| Jambeck et al. 2015. Plastic waste inputs from land into the ocean. Science. 374(6223): 768-771 	| Modeled on a per country basis 	| 2010 	|
|  	|  	|  	| http://science.sciencemag.org/content/347/6223/768.full.pdf+html 	|  	|  	|
| 8 	| LE ECO 	| Eurostat regional (NUTS3) GDP Data 	| downloaded on 12 May 2016 from Eurostat database nama_10r_3gdp. Nominal GDP data in millions of Euros 	| NUTS3 	| 2000 -2013 	|
|  	|  	|  	| http://ec.europa.eu/eurostat/data/database?p_auth=EgN81qAf&p_p_id=estatsearchportlet_WAR_estatsearchportlet&p_p_lifecycle=1&p_p_state=maximized&p_p_mode=view&_estatsearchportlet_WAR_estatsearchportlet_action=search&text=nama_10r_3gdp 	|  	|  	|
| 9 	| LE ECO 	| National GDP data 	| Eurostat Country GDP data Data downloaded 22 March 2016 from Eurostat Database nama_10_gdp. Nominal GDP in millions of Euros. 	| EU countries 	| 2000-2015 	|
|  	|  	|  	| http://ec.europa.eu/eurostat/data/database?p_auth=sHLAepWT&p_p_id=estatsearchportlet_WAR_estatsearchportlet&p_p_lifecycle=1&p_p_state=maximized&p_p_mode=view&_estatsearchportlet_WAR_estatsearchportlet_action=search&text=nama_10_gdp 	|  	|  	|
| 10 	| LE ECO 	| National GDP data 	| Eurostat database naida_10_gdp. Download criteria: Russia; Gross domestic product at market prices; CP_MEUR (Current prices, million euro ); 2000-2014 	| Russia 	| 2000-2014 	|
|  	|  	|  	| http://ec.europa.eu/eurostat/web/products-datasets/-/naida_10_gdp 	|  	|  	|
| 11 	| LE ECO, 	| Population density 	| Population density data obtained from the HYDE database 	| European countries 	| 2005 	|
|  	| LE LIV, 	|  	| http://themasites.pbl.nl/tridion/en/themasites/hyde/download/index-2.html 	|  	|  	|
|  	| TR 	|  	|  	|  	|  	|
|  	|  	|  	| Year of data = 2005. Data were a 5' resolution. Erik Smedberg with the Baltic Sea Center re-gridded to a 10 x 10 km grid. 	|  	|  	|
|  	|  	|  	| Population density within a 25km buffer from the coast will be used. 	|  	|  	|
|  	|  	|  	| References: Klein Goldewijk, K. , A. Beusen, M. de Vos and G. van Drecht (2011). The HYDE 3.1 spatially explicit database of human induced land use change over the past 12,000 years, Global Ecology and Biogeography20(1): 73-86. DOI: 10.1111/j.1466-8238.2010.00587.x. 	|  	|  	|
|  	|  	|  	| Klein Goldewijk, K. , A. Beusen, and P. Janssen (2010). Long term dynamic modeling of global population and built-up area in a spatially explicit way, HYDE 3 .1. The Holocene20(4):565-573. http://dx.doi.org/10.1177/0959683609356587 	|  	|  	|
| 12 	| LE ECO, 	| National population size, EU countries 	| Downloaded on March 31 2016 from Eurostat database demo_gind 	| EU countries 	| 1990-2015 	|
|  	| LE LIV, 	|  	| http://ec.europa.eu/eurostat/data/database?p_auth=whAQQAX7&p_p_id=estatsearchportlet_WAR_estatsearchportlet&p_p_lifecycle=1&p_p_state=maximized&p_p_mode=view&_estatsearchportlet_WAR_estatsearchportlet_action=search&text=demo_gind 	|  	|  	|
|  	| TR 	|  	|  	|  	|  	|
| 13 	| LE ECO, 	| Russian population size 	| Downloaded on 10 June 2016 from Eurostat database: naida_10_pe population and employment (thousands of people) 	| Russia 	| 2000-2011 	|
|  	| LE LIV, 	| end employment 	| http://ec.europa.eu/eurostat/web/products-datasets/-/naida_10_pe 	|  	|  	|
|  	| TR 	|  	|  	|  	|  	|
| 14 	| LE LIV 	| Percent Employed 	| Data downloaded on 31 March 2016 from Eurostat database lfst_r_lfe2emprt. 	| NUTS0 (country) and NUTS2 	| 1999-2014 	|
|  	|  	|  	| http://ec.europa.eu/eurostat/data/database?p_auth=BgwyNWIM&p_p_id=estatsearchportlet_WAR_estatsearchportlet&p_p_lifecycle=1&p_p_state=maximized&p_p_mode=view&_estatsearchportlet_WAR_estatsearchportlet_action=search&text=lfst_r_lfe2emprt 	|  	|  	|
|  	|  	|  	| ages 15-64; All sexes 	|  	|  	|
| 15 	| FP MAR 	| Rainbow trout production, Sweden 	| Jorbruksverket 	| Sub-country level – 3 major regions 	| 2001-2014 	|
|  	|  	|  	| http://www.scb.se/sv_/Hitta-statistik/Statistik-efter-amne/Jord--och-skogsbruk-fiske/Vattenbruk/Vattenbruk/ 	|  	|  	|
| 16 	| FP MAR 	| Rainbow trout production, Denmark 	| Danish Agrifish Agency (Ministry of Environment and Food of Denmark) 	|  	| 2006-2014 	|
|  	|  	|  	| http://agrifish.dk/fisheries/fishery-statistics/aquaculture-statistics/#c32851 	|  	|  	|
| 17 	| FP MAR 	| Rainbow trout production, Finland 	| Finnish Natural Resources Institute 	| National rainbow trout production allocated among major Finnish regions based on the relative proportion of total mariculture production among regions 	| 2005-2014 	|
|  	|  	|  	| LINK HAS BROKEN, was (http://statdb.luke.fi/PXWeb/pxweb/fi/LUKE/LUKE__06%20Kala%20ja%20riista__02%20Rakenne%20ja%20tuotanto__10%20Vesiviljely/?tablelist=true&rxid=5211d344-451e-490d-8651-adb38df626e1) 	|  	|  	|
|  	|  	|  	| --Data were available as total marine production by region.  Data were also available as total production per fish species.  Rainbow trout dominated the total fish production.  Ginnette converted the total production by region to rainbow trout production by region by using the country wide percent rainbow trout of the marine production in each year.  (The other minor contributions to total production were European whitefish, Trout, other species, Roe of rainbow trout, roe of european whitefish). 	|  	|  	|
| 18 	| FP MAR 	| Rainbow trout production, Germany 	| FAO FishStatJ Global workspace, Aquaculture Production (Quantities and values) 1950-2014 (Release date: March 2016). Download 15 June 2016 	| Country 	| 2005-2014 	|
|  	|  	|  	| http://www.fao.org/fishery/statistics/software/fishstatj/en#downlApp 	|  	|  	|
| 19 	| FP MAR 	| Sustainability coefficient 	| Rainbow trout SMI is only included for Sweden. Mean of three subindices (waste water treatment, usage of fishmeal and hatchery vs wild origin of seeds) from the  Mariculture Sustainability Index. 	| Country 	|  	|
|  	|  	|  	| Trujillo, P., (2008). Using a mariculture sustainability index to rank countries’ performance. Pp. 28-56 In: Alder, J. and D. Pauly (eds.). 2008.  A comparative assessment of biodiversity, fisheries and aquaculture in 53 countries’ Exclusive Economic Zones.’ Fisheries Centre Research Reports. Fisheries Centre, University of British Columbia 	|  	|  	|
| 20 	| FP FIS 	| Landings 	| Annual Landings by ICES area and stock . 	| ICES area 	|  	|
| 21 	| BD SPP 	| HELCOM redlist 	| Complete redlist excel file emailed by Joni Kaitaranta (HELCOM) on 14 June 2016. 	| Baltic Sea 	| 2013 	|
|  	|  	|  	| See also: 	|  	|  	|
|  	|  	|  	| HELCOM. 2013. HELCOM Red List of Baltic Sea species in danger of becoming extinct. Balt. Sea Environ. Proc. No. 140 	|  	|  	|
| 22 	| BD SPP 	| Checklists of 	| Available at: 	| Baltic Sea basins 	| Updated as of 2012-2013 	|
|  	|  	| Benthic invertebrates, 	| http://helcom.fi/baltic-sea-trends/biodiversity/red-list-of-species 	|  	|  	|
|  	|  	| Fish and lamprey species, macrophytes, 	|  	|  	|  	|
|  	|  	| Marine mammals, breeding birds (these data not used). 	| Downloaded on 14 June 2016. 	|  	|  	|
|  	|  	|  	| Also see: 	|  	|  	|
|  	|  	|  	| HELCOM 2012. Checklist of Baltic Sea Macro-species. Baltic Sea Environment Proceedings No. 130 	|  	|  	|
| 23 	| TR 	| Nights spent at tourist accommodation establishments by all NUTS regions with the finest scale spatial resolution at NUTS2 	| Eurostat dataset tour_occ_nin2 	|  	| 1990-2014 	|
|  	|  	|  	| http://appsso.eurostat.ec.europa.eu/nui/show.do?dataset=tour_occ_nin2&lang=en 	| NUTS2 	|  	|
|  	|  	|  	| Downloaded: 10 Feb 2016 	|  	|  	|
| 24 	| TR 	| Nights spent at tourist accommodation establishments by coastal and non-coastal area from 2012 onward 	| Eurostat dataset tour_occ_nin2c 	| NUTS1 (variable NUTS levels available by country, NUTS1 consistently available) 	| 2012-2014 	|
|  	|  	|  	| Downloaded: 10 Feb 2016 	|  	|  	|
|  	|  	|  	| http://appsso.eurostat.ec.europa.eu/nui/show.do?dataset=tour_occ_nin2c&lang=en 	|  	|  	|
| 25 	| Pressure 	| Summer surface temperature (0-5 m); annual surface salinity (0-m ); annual deep water salinity (depth is basin specific) 	| Data are from the BALTSEM model, run by Bärbel Müller Karulis from the Baltic Sea Centre at Stockholm University. 	| BALTSEM basins for the Baltic Sea 	| 1960-2100 	|
|  	|  	|  	| http://www.balticnest.org/balticnest/thenestsystem/baltsem.4.3186f824143d05551ad20ea.html 	|  	|  	|
|  	|  	|  	| Projections are use with forcing from the ECHAM5 global climate model for the scenario A1b. Projections go to year 2100. 	|  	|  	|
| 26 	| Pressure 	| Nitrogen and phosphorus load (including land-based and atmospheric sources, normalized for river flow) 	| Actual total (e.g. air and waterborne (direct and point source discharges)) annual input of nitrogren and phosphorous (tonnes) can be accessed here (http://helcom.fi/helcom-at-work/projects/completed-projects/plc-5-5/) . As loads are very sensitive to runoff, we use the flow-normalized input values. These data are plotted as the solid black line in Figure 3 under Results - HELCOM Core Indicator Inputs of Nitrogen and Phosphorus to the basins (http://www.helcom.fi/baltic-sea-trends/indicators/inputs-of-nitrogen-and-phosphorus-to-the-basins/results/). 	| Baltic Sea major basins 	| 1997-2003 (reference period);  2010-2012 current conditions 	|
|  	|  	|  	| MAI values for each basin are found in Summary report on the development of revised Maximum Allowable Inputs (MAI) and updated Country Allocated Reduction Targets (CART) of the Baltic Sea Action Plan in Table 3, p. 8. (http://www.helcom.fi/Documents/Ministerial2013/Associated%20documents/Supporting/Summary%20report%20on%20MAI-CART.pdf) 	|  	|  	|
| 27 	| Pressure 	| Atmospheric deposition of PCB-153 on the Baltic Sea 	| http://www.helcom.fi/baltic-sea-trends/environment-fact-sheets/hazardous-substances/atmospheric-deposition-of-pcb-153-on-the-baltic-sea/ 	| Baltic Sea major basins 	| 1990-2013 	|
| 28 	| Pressure 	| Atmospheric deposition of PCDD/Fs on the Baltic Sea 	| http://www.helcom.fi/baltic-sea-trends/environment-fact-sheets/hazardous-substances/atmospheric-deposition-of-pcdd-fs-on-the-baltic-sea/ 	| Baltic Sea major basins 	| 1990-2012 	|
| 29 	| Pressure, 	| Worldwide Governance Indicators (WGI) 	| The Worldwide Governance Indicators (WGI) project reports aggregate and individual governance indicators for 215 economies over the period 1996–2014, for six dimensions of governance: 	| Country 	| 1996 -2013 	|
|  	| Resilience 	|  	|  	|  	| Time series is broken, not observation for every year 	|
|  	|  	|  	| Voice and Accountability, Political Stability and Absence of Violence/Terrorism, Government Effectiveness, Regulatory Quality, Rule of Law, Control of Corruption 	|  	|  	|
|  	|  	|  	| Prepared by OHI https://github.com/OHI-Science/ohiprep/tree/master/globalprep/worldbank_wgi/intermediate 	|  	|  	|
| 30 	| Resilience 	| Goal-specific regulation analysis 	| See analysis of EU regulations and Baltic regional agreements for compliance for BHI by Joana Pedroso. International agreements were evaluated for existence only by Jennifer Griffiths based upon a country being a signatory of the international agreement 	| Country 	|  	|
| 31 	| CW CON 	| PFOS concentrations in herring liver and muscle tissue 	| ICES DOME database 	| unique lat,lon locations 	| 2005-2014 	|
|  	|  	|  	| http://dome.ices.dk/views/ContaminantsBiota.aspx 	|  	|  	|
|  	|  	|  	| Downloaded on 15 July 2016 	|  	|  	|
